# Generated by Django 4.0.3 on 2022-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание места устанвки'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='size',
            field=models.CharField(max_length=150, verbose_name='Размер уастка сот.'),
        ),
    ]
