# Generated by Django 4.0.3 on 2022-04-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_location_description_alter_yard_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlinterface',
            options={'ordering': ['name'], 'verbose_name': 'Интерфейс ОБОРУДОВАНИЯ', 'verbose_name_plural': 'Интерфейсы ОБОРУДОВАНИЯ'},
        ),
        migrations.AddField(
            model_name='building',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlinterface',
            name='count_pins',
            field=models.IntegerField(default=0, verbose_name='Количество входов/выходов'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='interface',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='home.controlinterface', verbose_name='Интерфейс управления'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование оборудования'),
        ),
    ]
