# Generated by Django 4.0.3 on 2022-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_controlinterface_options_building_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='smart_home.jpg', null=True, upload_to='home/image/', verbose_name='Изображение'),
        ),
    ]
