# Generated by Django 4.0.3 on 2022-04-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_house_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Land',
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['name'], 'verbose_name': 'Земельный уасток', 'verbose_name_plural': 'Земельные уастки'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='house',
            new_name='land',
        ),
        migrations.AddField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='home.building', verbose_name='Здание в котором установлено'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='home.land', verbose_name='Земельный уасток где установлено'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='home.room', verbose_name='Помещение в котором установлено'),
        ),
        migrations.DeleteModel(
            name='Yard',
        ),
    ]
