# Generated by Django 4.0.3 on 2022-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_land_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, default='home/image/2270995_2x.jpg', null=True, upload_to='home/image/', verbose_name='Изображение'),
        ),
    ]
