# Generated by Django 4.0.3 on 2022-04-18 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Размер участка в сотках'),
        ),
    ]
