# Generated by Django 4.0.3 on 2022-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_land_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(default='Не указано', max_length=150, verbose_name='Место нахождения'),
        ),
    ]
