# Generated by Django 4.0.3 on 2022-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_land_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(default='Местонахождение не указано', max_length=150, verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
