# Generated by Django 4.0.3 on 2022-04-18 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_alter_land_address_alter_land_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(default='Местонахождение не указано', help_text='Укажите местонахождение земельного уастка', max_length=150, verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='land',
            name='author',
            field=models.ForeignKey(help_text='Обязательно', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, help_text='Не обязательно', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, default='home/image/2270995_2x.jpg', help_text='Изображение для участка (Необязательно)', null=True, upload_to='home/image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(help_text='Обязательно', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.IntegerField(blank=True, default=0, help_text='Не обязательно', null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Размер участка в сотках'),
        ),
    ]
