# Generated by Django 4.0.3 on 2022-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_building_image_controlinterface_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Сенсор/датчик', 'Сенсор/датчик'), ('Контролируемый параметр', 'Контролируемый параметр'), ('Управляемое устройство', 'Управляемое устройство'), ('Управляемое устройство с обратной связью', 'Управляемое устройство с обратной связью')], default='Управляемое устройство', max_length=50),
        ),
    ]
