# Generated by Django 4.0.3 on 2022-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Марка и модель оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Подраобное описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Общее название'),
        ),
    ]
