# Generated by Django 4.0.3 on 2022-05-01 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0018_alter_manufacturer_options'),
        ('home', '0014_equipment_model_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associstions', to=settings.AUTH_USER_MODEL)),
                ('device_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associstions', to='device.input', verbose_name='Вход прибора УД')),
                ('device_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associstions', to='device.interface', verbose_name='Интерфейс прибора УД')),
                ('device_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associstions', to='device.output', verbose_name='Выход прибора УД')),
                ('equipment_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associstions', to='home.controlinterface', verbose_name='Интерфейс оборудования')),
            ],
        ),
    ]
