# Generated by Django 4.0.3 on 2022-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_alter_manufacturer_options'),
        ('home', '0016_alter_association_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='association',
            name='add_favorite',
        ),
        migrations.RemoveField(
            model_name='association',
            name='device_input',
        ),
        migrations.AddField(
            model_name='association',
            name='device_input',
            field=models.ManyToManyField(blank=True, related_name='associstions', to='device.input', verbose_name='Вход прибора УД'),
        ),
        migrations.RemoveField(
            model_name='association',
            name='device_output',
        ),
        migrations.AddField(
            model_name='association',
            name='device_output',
            field=models.ManyToManyField(blank=True, related_name='associstions', to='device.output', verbose_name='Выход прибора УД'),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('equipment_interface', 'device_interface'), name='add_favorite'),
        ),
    ]
