# Generated by Django 4.0.3 on 2022-05-02 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_association_add_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='interface',
        ),
        migrations.AddField(
            model_name='equipment',
            name='control',
            field=models.ManyToManyField(blank=True, related_name='equipments', through='home.QuantityInterface', to='home.controlinterface', verbose_name='Интерфейс управления'),
        ),
        migrations.AddField(
            model_name='quantityinterface',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_interfaces', to='home.equipment'),
        ),
        migrations.AddField(
            model_name='quantityinterface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_interfaces', to='home.controlinterface'),
        ),
        migrations.AddConstraint(
            model_name='quantityinterface',
            constraint=models.UniqueConstraint(fields=('interface', 'equipment'), name='unicue_equipment_interface'),
        ),
    ]
