# Generated by Django 4.0.3 on 2022-05-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_quantityinterface_remove_equipment_interface_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quantityinterface',
            name='unicue_equipment_interface',
        ),
    ]
