# Generated by Django 4.0.3 on 2022-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_controlinterface_count_pins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='home.location', verbose_name='Места возможной установки'),
        ),
    ]
