# Generated by Django 4.0.3 on 2022-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_equipment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinterface',
            name='image',
            field=models.ImageField(default='home/image/smart_home.jpg', help_text='Схема (Необязательно)', upload_to='home/image/', verbose_name='Изображение'),
        ),
    ]
