# Generated by Django 4.0.3 on 2022-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_controlinterface_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlinterface',
            name='image',
            field=models.ImageField(blank=True, help_text='Схема (Необязательно)', null=True, upload_to='home/image/', verbose_name='Изображение'),
        ),
    ]
