# Generated by Django 4.0.3 on 2022-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_controlinterface_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='start_current',
        ),
        migrations.AlterField(
            model_name='controlinterface',
            name='current',
            field=models.IntegerField(default=0, verbose_name='Мощность Вт'),
        ),
        migrations.AlterField(
            model_name='controlinterface',
            name='start_current',
            field=models.IntegerField(default=0, help_text='Зависит от типа устройства </br> Лампы накаливания I=Inom*10, </br> Светодиодные "хорошие" I=Inom*20, </br> Светодиодные "плохие" I=Inom*200, </br> Электродвигатели I=Inom*5,', verbose_name='Стартовый ток А'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current',
            field=models.IntegerField(default=0, verbose_name='Потребление тока Вт'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='voltage',
            field=models.IntegerField(default=0, verbose_name='Напряжение питания. Без учета управляющего напряжения'),
        ),
    ]
