# Generated by Django 4.0.3 on 2022-04-15 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название устрройства')),
                ('description', models.TextField(max_length=500, verbose_name='Описание устройства')),
                ('unit', models.IntegerField(default=0, verbose_name='Количество юнитов занимаемое устройством')),
                ('voltage', models.IntegerField(default=0, verbose_name='Напряжение питания В')),
                ('current', models.IntegerField(default=0, verbose_name='Потребление тока Вт')),
                ('price', models.IntegerField(default=0, verbose_name='Цена Р')),
            ],
            options={
                'verbose_name': 'Smart Home Устройство',
                'verbose_name_plural': 'Smart Home Устройства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название интерфейса')),
                ('description', models.TextField(max_length=200, verbose_name='Описание интерфейса')),
            ],
            options={
                'verbose_name': 'Интерфейс',
                'verbose_name_plural': 'Интерфейсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование входа/выхода')),
                ('description', models.TextField(max_length=200, verbose_name='Описание входа/выхода')),
                ('voltage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коммутируемое напряжение')),
                ('nominal_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номинальный коммутируемый ток')),
                ('maximal_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальный коммутируемый ток')),
                ('starting_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Пусковой ток')),
            ],
            options={
                'verbose_name': 'Вход/выход',
                'verbose_name_plural': 'Входы/выходы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmartSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя системы УД')),
                ('description', models.TextField(max_length=200, verbose_name='Описание системы УД')),
            ],
            options={
                'verbose_name': 'Система УД',
                'verbose_name_plural': 'Системы УД',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuantityPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество входов/выходов')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_pins', to='device.device')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_pins', to='device.pins')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='interface',
            field=models.ManyToManyField(blank=True, related_name='devices', to='device.interface', verbose_name='Интерфейс'),
        ),
        migrations.AddField(
            model_name='device',
            name='pin',
            field=models.ManyToManyField(blank=True, related_name='входы_выходы', through='device.QuantityPin', to='device.pins', verbose_name='Пины'),
        ),
        migrations.AddField(
            model_name='device',
            name='specific',
            field=models.ManyToManyField(blank=True, related_name='devices', to='device.smartsystem', verbose_name='К какой системе относится'),
        ),
    ]
