# Generated by Django 4.0.3 on 2022-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(default='default_device.jpg', upload_to='static/image/', verbose_name='Изображение'),
        ),
    ]
