# Generated by Django 4.0.3 on 2022-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(default='default_device.jpg', upload_to='media/image/', verbose_name='Изображение'),
        ),
    ]
