# Generated by Django 4.0.3 on 2022-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default='default_device.jpg', null=True, upload_to='device/image/', verbose_name='Изображение'),
        ),
    ]
