# Generated by Django 4.0.3 on 2022-04-16 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество входов/выходов')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество входов/выходов')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='pin',
        ),
        migrations.AddField(
            model_name='device',
            name='input',
            field=models.ManyToManyField(blank=True, related_name='devices_in', through='device.QuantityInput', to='device.pins', verbose_name='Входы'),
        ),
        migrations.AddField(
            model_name='device',
            name='output',
            field=models.ManyToManyField(blank=True, related_name='devices_out', through='device.QuantityOutput', to='device.pins', verbose_name='Выходы'),
        ),
        migrations.DeleteModel(
            name='QuantityPin',
        ),
        migrations.AddField(
            model_name='quantityoutput',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_outputs', to='device.device'),
        ),
        migrations.AddField(
            model_name='quantityoutput',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_outputs', to='device.pins'),
        ),
        migrations.AddField(
            model_name='quantityinput',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_inputs', to='device.device'),
        ),
        migrations.AddField(
            model_name='quantityinput',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_inputs', to='device.pins'),
        ),
    ]
