# Generated by Django 4.0.3 on 2022-04-16 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_quantityinput_quantityoutput_remove_device_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='short_description',
            field=models.TextField(default=0, max_length=200, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantityinput',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество входов'),
        ),
        migrations.AlterField(
            model_name='quantityoutput',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0')], verbose_name='Количество выходов'),
        ),
    ]
