# Generated by Django 4.0.3 on 2022-04-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_controlinterface_options_building_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0009_device_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interface',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartsystem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_sustems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Полное описание'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование входа/выхода')),
                ('description', models.TextField(max_length=200, verbose_name='Описание входа/выхода')),
                ('voltage_ac', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коммутируемое переменное напряжение')),
                ('voltage_dc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коммутируемое постоянное напряжение')),
                ('nominal_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номинальный коммутируемый ток')),
                ('maximal_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальный коммутируемый ток')),
                ('starting_current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Пусковой ток')),
                ('pwm_frequency', models.IntegerField(blank=True, default=0, null=True, verbose_name='Частота ШИМ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выход',
                'verbose_name_plural': 'Выходы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование входа/выхода')),
                ('description', models.TextField(max_length=200, verbose_name='Описание входа/выхода')),
                ('purpose', models.TextField(max_length=500, verbose_name='Назначение входа')),
                ('general_purpose', models.BooleanField(default=0, verbose_name='Вход общего назначения')),
                ('counting_signals', models.BooleanField(default=0, verbose_name='Счет сигналов')),
                ('frequency_measurement', models.BooleanField(default=0, verbose_name='Измерение частоты')),
                ('direct_control', models.BooleanField(default=0, verbose_name='Прямое управление реле')),
                ('mapping_matrix', models.BooleanField(default=0, verbose_name='Настройка с помощью mapping-матрицы')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вход',
                'verbose_name_plural': 'Входы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='input',
            field=models.ManyToManyField(blank=True, related_name='devices_in', through='device.QuantityInput', to='device.input', verbose_name='Входы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='output',
            field=models.ManyToManyField(blank=True, related_name='devices_out', through='device.QuantityOutput', to='device.output', verbose_name='Выходы'),
        ),
        migrations.AlterField(
            model_name='quantityinput',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_inputs', to='device.input'),
        ),
        migrations.AlterField(
            model_name='quantityoutput',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_outputs', to='device.output'),
        ),
        migrations.DeleteModel(
            name='Pins',
        ),
    ]
