# Generated by Django 4.0.3 on 2022-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_device_author_interface_author_smartsystem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='dry_contact',
            field=models.BooleanField(default=False, verbose_name='"Сухой" контакт'),
        ),
        migrations.AddField(
            model_name='output',
            name='type',
            field=models.CharField(choices=[('RELAY_NO_C', 'Реле NO/C'), ('RELAY_NC_C', 'Реле NC/C'), ('RELAY_NC_C_NO', 'Реле NC/C/NO'), ('PWM', 'ШИМ'), ('HZ', 'ХЗ')], default='HZ', max_length=15),
        ),
        migrations.AlterField(
            model_name='input',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание входа'),
        ),
        migrations.AlterField(
            model_name='input',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование входа'),
        ),
        migrations.AlterField(
            model_name='input',
            name='purpose',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Назначение входа'),
        ),
        migrations.AlterField(
            model_name='output',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание выхода'),
        ),
        migrations.AlterField(
            model_name='output',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование выхода'),
        ),
    ]
