# Generated by Django 4.0.3 on 2022-04-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_output_dry_contact_output_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='dry_contact',
        ),
    ]
