# Generated by Django 4.0.3 on 2022-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_remove_output_dry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='type',
            field=models.CharField(choices=[('Реле двухпозиционное, нормально ОТкрытое (NO C)', 'Реле NO/C'), ('Реле двухпозиционное, нормально ЗАкрытое (NC C)', 'Реле NC/C'), ('Реле трезпозиционное (NC C NO)', 'Реле NC/C/NO'), ('Широтно Импульсная Модуляция (ШИМ)', 'ШИМ'), ('Неизвестно', 'ХЗ')], default='Неизвестно', max_length=50),
        ),
    ]
