# Generated by Django 4.0.3 on 2022-04-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_manufacturer_device_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='site',
            field=models.URLField(default=0, max_length=100, verbose_name='Сайт компании'),
            preserve_default=False,
        ),
    ]
