# Generated by Django 4.0.3 on 2022-04-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_manufacturer_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['title'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
