# Generated by Django 4.0.3 on 2022-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
