# Generated by Django 4.0.3 on 2022-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_alter_device_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default='device/image/default_device.jpg', null=True, upload_to='device/image/', verbose_name='Изображение'),
        ),
    ]
